" Automatic reloading of .vimrc
augroup relaod_vimrc " {
    autocmd!
    autocmd BufWritePost $MYVIMRC source $MYVIMRC
augroup END " }

" *****************************************************************************
"  Load my custom settings
" *****************************************************************************

source $XDG_CONFIG_HOME/vim/.vim/startup/settings.vim
source $XDG_CONFIG_HOME/vim/.vim/startup/functions.vim
source $XDG_CONFIG_HOME/vim/.vim/startup/mappings.vim

