#!/bin/sh

userresources="$XDG_CONFIG_HOME"/X11/xresources
sysresources=/etc/X11/xinit/.Xresources

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

# set the keyboard layout and options
setxkbmap -model pc105 -layout de -variant nodeadkeys -option caps:escape,compose:paus,lv3:ralt_switch,eurosign:e
numlockx on

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

if [[ $1 == "kde" ]]
then
    exec /usr/bin/startplasma-x11
else
    xbindkeys -f "$XDG_CONFIG_HOME"/xbindkeys/xbindkeysrc
    exec qtile
fi

