# OKSolar (light): https://meat.io/oksolar

# Default colors
[colors.primary]
background = "#fbf7ef"
foreground = "#5b7279"

# Normal colors
[colors.normal]
black   = "#fbf7ef"
red     = "#f23749"
green   = "#819500"
yellow  = "#ac8300"
blue    = "#2b90d8"
magenta = "#dd459d"
cyan    = "#259d94"
white   = "#5b7279"

# Bright colors
[colors.bright]
black   = "#f1e9d2"
red     = "#f23749"
green   = "#819500"
yellow  = "#ac8300"
blue    = "#2b90d8"
magenta = "#dd459d"
cyan    = "#259d94"
white   = "#002d38"

# Indexed colors
[colors]
indexed_colors = [
    { index = 16, color = "#d56500" },
    { index = 17, color = "#7d80d1" },
    { index = 18, color = "#98a8a8" },
    { index = 19, color = "#8faaab" },
    { index = 20, color = "#657377" },
    { index = 21, color = "#093946" },
]

