#!/usr/bin/bash

# -----------------------------------------------------------------------------
# This script takes care of my initial screen setup durint startup. Since it is
# very special to my personal setup (monitors, hostnames of my machines, etc.,
# it is probably not useful for anyone else.
#
# Depending on the hostname and the number of active monitors it calls
# different scripts. There names follow the convention:
# <HOSTNAME>_internal-<NUM_INTERNAL_MONITORS>_external-<NUM_EXTERNAL_MONITORS>.sh
# 
# These scrips were generated by **arandr** and use **xranr**, to set up my
# monitors/screens.
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# actual script
# -----------------------------------------------------------------------------

LAYOUT_SCRIPT_DIR="$XDG_DATA_HOME/screenlayouts"

hostname=`hostname`
num_monitors=`xrandr --listactivemonitors | head -n 1 | cut -d " " -f2`

# Assuming that the lid of a laptop is open, when you start the laptop, one of
# the monitors will be the internal laptop monitor. Therefore:
num_internal_monitors=1
num_external_monitors=$((num_monitors - num_internal_monitors))

layout_script_name=`printf \
    "%s_internal-%d_external-%d.sh"\
    $hostname \
    $num_internal_monitors \
    $num_external_monitors`

layout_script_path="$LAYOUT_SCRIPT_DIR/$layout_script_name"

if [ -f $layout_script_path ]
then
    $layout_script_path
fi
