require "user.plugins-setup"
require "user.core.options"
require "user.core.keymaps"
require "user.core.colorscheme"

require "user.plugins.nvim-cmp"
require "user.plugins.nvim-tree"
require "user.plugins.lualine"
require "user.plugins.telescope"
require "user.plugins.treesitter"
require "user.plugins.autopairs"
require "user.plugins.mason"
require "user.plugins.lspsaga"
require "user.plugins.lspconfig"
