require "user.options"
require "user.plugins"
require "user.keymaps"
require "user.colorscheme"

require "user.plugins.nvim-cmp"
require "user.plugins.nvim-tree"
require "user.plugins.lualine"
require "user.plugins.telescope"
require "user.plugins.treesitter"
require "user.plugins.autopairs"
require "user.plugins.mason"
